# CRM Leads — Complete Data Cleaning Notebook

## Objective
Clean the CRM Leads dataset for analysis and Power BI.

### Rules used
1. Replace missing values wherever replacement is meaningful.
2. Do not delete rows because of missing values.
3. Convert date/time columns into the correct format.
4. Convert numeric columns into appropriate numeric data types.
5. Standardize text and categorical values.
6. Handle invalid negative revenue values.
7. Check duplicate rows without automatically deleting them.
8. Validate the dataset after cleaning.
9. Export the cleaned dataset for Power BI.

## Load raw lead data

In [560]:
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Desktop\Group project\Data set\CRM Leads (2).csv")

## Display first 5 rows

In [561]:
df.head()

,Won Date,Lead Date,Lead Owner,Lead Source,Campaign Name,Won Revenue,Qualification,Preferred Location,Email Address,Lead Stage,...,Domain Interested,Coding Basics,ad set name,ad name,Created Username,Created Time,Updated Username,Updated Time,Viewed Username,Viewed Time
0,04-Sep-26,04-Sep-26,Bridgeon Admin,Kodlar CRM Tech Lead,NaN,0.0,--Select--,-Other-,NaN,CLOSED LOST,...,Python Full Stack,No,NaN,NaN,Bridgeon Admin,04-09-2026 14:30,Bridgeon Admin,04-09-2026 14:30,Bridgeon Admin,04-09-2026 14:30
1,04-Sep-26,04-Sep-26,Bridgeon Admin,Kodlar CRM Tech Lead,NaN,0.0,--Select--,-Other-,NaN,CLOSED LOST,...,Python Full Stack,No,NaN,NaN,Bridgeon Admin,04-09-2026 14:12,Bridgeon Admin,04-09-2026 14:12,Bridgeon Admin,04-09-2026 14:12
2,04-Sep-26,04-Sep-26,Bridgeon Admin,Kodlar CRM Tech Lead,NaN,0.0,--Select--,-Other-,NaN,CLOSED LOST,...,Python Full Stack,No,NaN,NaN,Bridgeon Admin,04-09-2026 14:01,Bridgeon Admin,04-09-2026 14:01,Bridgeon Admin,04-09-2026 14:01
3,04-Sep-26,04-Sep-26,Bridgeon Admin,Kodlar CRM Tech Lead,NaN,0.0,--Select--,-Other-,NaN,CLOSED LOST,...,Python Full Stack,No,NaN,NaN,Bridgeon Admin,04-09-2026 13:59,Bridgeon Admin,04-09-2026 13:59,Bridgeon Admin,04-09-2026 13:59
4,04-Sep-26,04-Sep-26,Bridgeon Admin,Kodlar CRM Tech Lead,NaN,0.0,--Select--,-Other-,NaN,CLOSED LOST,...,Python Full Stack,No,NaN,NaN,Bridgeon Admin,04-09-2026 13:45,Bridgeon Admin,04-09-2026 13:45,Bridgeon Admin,04-09-2026 13:45

## **Dataset Shape Before Cleaning**

In [562]:
print(df.shape)

(10000, 52)

## Column names

In [563]:
print(df.columns.tolist())

['Won Date', 'Lead Date', 'Lead Owner', 'Lead Source', 'Campaign Name', 'Won Revenue', 'Qualification', 'Preferred Location', 'Email Address', 'Lead Stage', 'Expected Closing Date', 'Won Description', 'Lost Reason', 'Lost Description', 'Update few words about this lead', 'Created By', 'Lead Automation Email', 'Lead ID', 'Lead Title', 'Campaign Term', 'Campaign Content', 'Contact Reference', 'Lead Assigned At', 'First Touch At', 'Call DID Status', 'Last Call Time', 'Caller Name', 'Call Duration', 'Call Feedback', 'Next Follow-up On', 'Next Follow-up Notes', 'Call Missed by User', 'Total_Outgoing_Calls', 'Total_Incoming_Calls', 'College', 'Program', 'Year of Pass', 'District', 'Lead Quality', 'UTM', 'Droped Date', 'Tomorrow closing', 'Domain Interested', 'Coding Basics', 'ad set name', 'ad name', 'Created Username', 'Created Time', 'Updated Username', 'Updated Time', 'Viewed Username', 'Viewed Time']

## Data types and non-null values

In [564]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 52 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Won Date                          7126 non-null   object
 1   Lead Date                         9982 non-null   object
 2   Lead Owner                        10000 non-null  object
 3   Lead Source                       10000 non-null  object
 4   Campaign Name                     2049 non-null   object
 5   Won Revenue                       1955 non-null   float64
 6   Qualification                     9980 non-null   object
 7   Preferred Location                10000 non-null  object
 8   Email Address                     5041 non-null   object
 9   Lead Stage                        10000 non-null  object
 10  Expected Closing Date             1 non-null      object
 11  Won Description                   96 non-null     object
 12  Lost Reason                       10000 non-null  object
 13  Lost Description                  1740 non-null   object
 14  Update few words about this lead  68 non-null     object
 15  Created By                        6672 non-null   object
 16  Lead Automation Email             0 non-null      float64
 17  Lead ID                           0 non-null      float64
 18  Lead Title                        4 non-null      object
 19  Campaign Term                     0 non-null      float64
 20  Campaign Content                  0 non-null      float64
 21  Contact Reference                 10000 non-null  object
 22  Lead Assigned At                  5995 non-null   object
 23  First Touch At                    4591 non-null   object
 24  Call DID Status                   9929 non-null   object
 25  Last Call Time                    4827 non-null   object
 26  Caller Name                       4827 non-null   object
 27  Call Duration                     4827 non-null   float64
 28  Call Feedback                     2 non-null      object
 29  Next Follow-up On                 3046 non-null   object
 30  Next Follow-up Notes              3418 non-null   object
 31  Call Missed by User               4960 non-null   object
 32  Total_Outgoing_Calls              0 non-null      float64
 33  Total_Incoming_Calls              0 non-null      float64
 34  College                           5152 non-null   object
 35  Program                           9991 non-null   object
 36  Year of Pass                      10000 non-null  object
 37  District                          9920 non-null   object
 38  Lead Quality                      10000 non-null  object
 39  UTM                               69 non-null     object
 40  Droped Date                       0 non-null      float64
 41  Tomorrow closing                  7 non-null      object
 42  Domain Interested                 10000 non-null  object
 43  Coding Basics                     10000 non-null  object
 44  ad set name                       2049 non-null   object
 45  ad name                           2049 non-null   object
 46  Created Username                  10000 non-null  object
 47  Created Time                      10000 non-null  object
 48  Updated Username                  10000 non-null  object
 49  Updated Time                      10000 non-null  object
 50  Viewed Username                   10000 non-null  object
 51  Viewed Time                       10000 non-null  object
dtypes: float64(9), object(43)
memory usage: 4.0+ MB

## Identify available columns

In [565]:
print("Available Columns:")
for col in df.columns:
    print(col)

Available Columns:
Won Date
Lead Date
Lead Owner
Lead Source
Campaign Name
Won Revenue
Qualification
Preferred Location
Email Address
Lead Stage
Expected Closing Date
Won Description
Lost Reason
Lost Description
Update few words about this lead
Created By
Lead Automation Email
Lead ID
Lead Title
Campaign Term
Campaign Content
Contact Reference
Lead Assigned At
First Touch At
Call DID Status
Last Call Time
Caller Name
Call Duration
Call Feedback
Next Follow-up On
Next Follow-up Notes
Call Missed by User
Total_Outgoing_Calls
Total_Incoming_Calls
College
Program
Year of Pass
District
Lead Quality
UTM
Droped Date
Tomorrow closing
Domain Interested
Coding Basics
ad set name
ad name
Created Username
Created Time
Updated Username
Updated Time
Viewed Username
Viewed Time

## Check missing values

In [566]:
missing = df.isnull().sum()
print(missing)

Won Date                             2874
Lead Date                              18
Lead Owner                              0
Lead Source                             0
Campaign Name                        7951
Won Revenue                          8045
Qualification                          20
Preferred Location                      0
Email Address                        4959
Lead Stage                              0
Expected Closing Date                9999
Won Description                      9904
Lost Reason                             0
Lost Description                     8260
Update few words about this lead     9932
Created By                           3328
Lead Automation Email               10000
Lead ID                             10000
Lead Title                           9996
Campaign Term                       10000
Campaign Content                    10000
Contact Reference                       0
Lead Assigned At                     4005
First Touch At                       5409
Call DID Status                        71
Last Call Time                       5173
Caller Name                          5173
Call Duration                        5173
Call Feedback                        9998
Next Follow-up On                    6954
Next Follow-up Notes                 6582
Call Missed by User                  5040
Total_Outgoing_Calls                10000
Total_Incoming_Calls                10000
College                              4848
Program                                 9
Year of Pass                            0
District                               80
Lead Quality                            0
UTM                                  9931
Droped Date                         10000
Tomorrow closing                     9993
Domain Interested                       0
Coding Basics                           0
ad set name                          7951
ad name                              7951
Created Username                        0
Created Time                            0
Updated Username                        0
Updated Time                            0
Viewed Username                         0
Viewed Time                             0
dtype: int64

## Show missing percentage

In [567]:
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Missing_Percent": missing_percent
})

missing_summary = missing_summary[missing_summary["Missing"] > 0]

missing_summary

                                  Missing  Missing_Percent
Won Date                             2874            28.74
Lead Date                              18             0.18
Campaign Name                        7951            79.51
Won Revenue                          8045            80.45
Qualification                          20             0.20
Email Address                        4959            49.59
Expected Closing Date                9999            99.99
Won Description                      9904            99.04
Lost Description                     8260            82.60
Update few words about this lead     9932            99.32
Created By                           3328            33.28
Lead Automation Email               10000           100.00
Lead ID                             10000           100.00
Lead Title                           9996            99.96
Campaign Term                       10000           100.00
Campaign Content                    10000           100.00
Lead Assigned At                     4005            40.05
First Touch At                       5409            54.09
Call DID Status                        71             0.71
Last Call Time                       5173            51.73
Caller Name                          5173            51.73
Call Duration                        5173            51.73
Call Feedback                        9998            99.98
Next Follow-up On                    6954            69.54
Next Follow-up Notes                 6582            65.82
Call Missed by User                  5040            50.40
Total_Outgoing_Calls                10000           100.00
Total_Incoming_Calls                10000           100.00
College                              4848            48.48
Program                                 9             0.09
District                               80             0.80
UTM                                  9931            99.31
Droped Date                         10000           100.00
Tomorrow closing                     9993            99.93
ad set name                          7951            79.51
ad name                              7951            79.51

## Clean text/categorical columns

In [568]:
df["Program"] = df["Program"].fillna("Unknown")
df["College"] = df["College"].fillna("Unknown")
df["Lead Source"] = df["Lead Source"].fillna("Unknown")
df["Lead Owner"] = df["Lead Owner"].fillna("Unknown")
df["Caller Name"] = df["Caller Name"].fillna("Unknown")
df["Call DID Status"] = df["Call DID Status"].fillna("Unknown")
df["Qualification"] = df["Qualification"].fillna("Unknown")
df["District"] = df["District"].fillna("Unknown")
df["Created By"] = df["Created By"].fillna("Unknown")
df["Lead Title"] = df["Lead Title"].fillna("Unknown")
df["Qualification"] = df["Qualification"].replace("--Select--", "Unknown")
df["Preferred Location"] = df["Preferred Location"].replace("-Other-", "Other")
df["Tomorrow closing"] = df["Tomorrow closing"].fillna("No")

## Replace placeholder values in Lost Reason

In [569]:
df["Lost Reason"] = df["Lost Reason"].replace(
    ["--None--", "--None --", "None", ""],
    "Not Applicable"
)
# Replace actual missing values
df["Lost Reason"] = df["Lost Reason"].fillna("Not Applicable")

## Replace Invalid Values in lead quality

In [570]:
df["Lead Quality"] = df["Lead Quality"].fillna("Unknown")
df["Lead Quality"] = df["Lead Quality"].replace(
    ["", "--Select--", "nan"], "Unknown"
)

## Replace Invalid Valuesin  program

In [571]:
df["Program"] = df["Program"].astype("string").str.strip()
df["Program"] = df["Program"].replace("---Select---", "Unknown")
df["Program"] = df["Program"].fillna("Unknown")

## Replace Invalid Values in year of pass

In [572]:
df["Year of Pass"] = df["Year of Pass"].fillna("Unknown")

df["Year of Pass"] = df["Year of Pass"].replace(
    ["", "--Select--", "nan"], "Unknown"
)

## Clean notes and descriptions

In [573]:
df["Won Description"] = df["Won Description"].fillna("No Information")

df["Lost Description"] = df["Lost Description"].fillna("No Information")

df["Call Feedback"] = df["Call Feedback"].fillna("No Information")

df["Next Follow-up Notes"] = df["Next Follow-up Notes"].fillna("No Information")

df["Update few words about this lead"] = df[
    "Update few words about this lead"
].fillna("No Information")

## Clean marketing columns

In [574]:
df["Campaign Name"] = df["Campaign Name"].fillna("No Campaign")

df["Campaign Term"] = df["Campaign Term"].fillna("Not Provided")

df["Campaign Content"] = df["Campaign Content"].fillna("Not Provided")

df["UTM"] = df["UTM"].fillna("Not Provided")

df["ad set name"] = df["ad set name"].fillna("No Ad Set")

df["ad name"] = df["ad name"].fillna("No Ad")

## Identifier / system fields

In [575]:
df["Lead Automation Email"] = df["Lead Automation Email"].fillna("Not Provided")

df["Lead ID"] = df["Lead ID"].fillna(
    pd.Series(
        [f"LEAD_{i:05d}" for i in range(1, len(df) + 1)],
        index=df.index
    )
)

## Clean numeric columns

In [576]:
df["Total_Outgoing_Calls"] = pd.to_numeric(
    df["Total_Outgoing_Calls"], errors="coerce"
).fillna(0)

df["Total_Incoming_Calls"] = pd.to_numeric(
    df["Total_Incoming_Calls"], errors="coerce"
).fillna(0)

df["Call Duration"] = pd.to_numeric(
    df["Call Duration"], errors="coerce"
).fillna(0)

## For revenue

In [577]:
df["Won Revenue"] = pd.to_numeric(
    df["Won Revenue"], errors="coerce"
).fillna(0)

# If there are negative revenues:
df.loc[df["Won Revenue"] < 0, "Won Revenue"] = 0

## Clean Year of Pass

In [578]:
df["Year of Pass"] = df["Year of Pass"].replace(
    "--Select--", "Unknown"
)
df["Year of Pass"] = df["Year of Pass"].fillna("Unknown")

## Clean date/time columns

In [579]:
date_columns = [
    "Won Date",
    "Lead Date",
    "Expected Closing Date",
    "Lead Assigned At",
    "First Touch At",
    "Last Call Time",
    "Next Follow-up On",
    "Droped Date",
    "Created Time",
    "Updated Time",
    "Viewed Time"
]

# Convert columns to datetime
for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        errors="coerce"
    )

C:\Users\user\AppData\Local\Temp\ipykernel_7540\881152101.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(
C:\Users\user\AppData\Local\Temp\ipykernel_7540\881152101.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(

## Replace missing dates

In [580]:
date_replacements = {
    "Won Date": "Not Won",
    "Lead Date": "Date Not Available",
    "Expected Closing Date": "Not Scheduled",
    "Lead Assigned At": "Not Assigned",
    "First Touch At": "No First Touch",
    "Last Call Time": "No Call Recorded",
    "Next Follow-up On": "No Follow-up",
    "Droped Date": "Not Dropped",
    "Created Time": "Not Available",
    "Updated Time": "Not Available",
    "Viewed Time": "Not Viewed"
}

for col, replacement in date_replacements.items():
    df[col] = df[col].dt.strftime("%Y-%m-%d")
    df[col] = df[col].fillna(replacement)

## Clean email

In [581]:
df["Email Address"] = df["Email Address"].fillna("Not Provided")

df["Email Address"] = (
    df["Email Address"]
    .astype(str)
    .str.strip()
    .str.lower()
)

## Clean Call Missed by User

In [582]:
df["Call Missed by User"] = df["Call Missed by User"].fillna("No")

## Check duplicates

In [583]:
df.duplicated().sum()

np.int64(0)

## Final missing-value check

In [584]:
df.isnull().sum()

Won Date                            0
Lead Date                           0
Lead Owner                          0
Lead Source                         0
Campaign Name                       0
Won Revenue                         0
Qualification                       0
Preferred Location                  0
Email Address                       0
Lead Stage                          0
Expected Closing Date               0
Won Description                     0
Lost Reason                         0
Lost Description                    0
Update few words about this lead    0
Created By                          0
Lead Automation Email               0
Lead ID                             0
Lead Title                          0
Campaign Term                       0
Campaign Content                    0
Contact Reference                   0
Lead Assigned At                    0
First Touch At                      0
Call DID Status                     0
Last Call Time                      0
Caller Name                         0
Call Duration                       0
Call Feedback                       0
Next Follow-up On                   0
Next Follow-up Notes                0
Call Missed by User                 0
Total_Outgoing_Calls                0
Total_Incoming_Calls                0
College                             0
Program                             0
Year of Pass                        0
District                            0
Lead Quality                        0
UTM                                 0
Droped Date                         0
Tomorrow closing                    0
Domain Interested                   0
Coding Basics                       0
ad set name                         0
ad name                             0
Created Username                    0
Created Time                        0
Updated Username                    0
Updated Time                        0
Viewed Username                     0
Viewed Time                         0
dtype: int64

In [585]:
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

## Verify rows and columns after cleaning

In [586]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10000
Columns: 52

In [587]:
df

,Won Date,Lead Date,Lead Owner,Lead Source,Campaign Name,Won Revenue,Qualification,Preferred Location,Email Address,Lead Stage,...,Domain Interested,Coding Basics,ad set name,ad name,Created Username,Created Time,Updated Username,Updated Time,Viewed Username,Viewed Time
0,2026-09-04,2026-09-04,Bridgeon Admin,Kodlar CRM Tech Lead,No Campaign,0.0,Unknown,Other,not provided,CLOSED LOST,...,Python Full Stack,No,No Ad Set,No Ad,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09
1,2026-09-04,2026-09-04,Bridgeon Admin,Kodlar CRM Tech Lead,No Campaign,0.0,Unknown,Other,not provided,CLOSED LOST,...,Python Full Stack,No,No Ad Set,No Ad,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09
2,2026-09-04,2026-09-04,Bridgeon Admin,Kodlar CRM Tech Lead,No Campaign,0.0,Unknown,Other,not provided,CLOSED LOST,...,Python Full Stack,No,No Ad Set,No Ad,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09
3,2026-09-04,2026-09-04,Bridgeon Admin,Kodlar CRM Tech Lead,No Campaign,0.0,Unknown,Other,not provided,CLOSED LOST,...,Python Full Stack,No,No Ad Set,No Ad,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09
4,2026-09-04,2026-09-04,Bridgeon Admin,Kodlar CRM Tech Lead,No Campaign,0.0,Unknown,Other,not provided,CLOSED LOST,...,Python Full Stack,No,No Ad Set,No Ad,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09,Bridgeon Admin,2026-04-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Not Won,2026-05-05,Rincy,Insta Ad,New Leads Campaign 21/12/2025,0.0,Diploma Others,Other,akshayavishnu690@gmail.com,CLOSED LOST,...,Python Full Stack,No,Lookalike qualified,ningalude qualification +2 ano,Bridgeon Admin,2026-05-05,Bridgeon Admin,Not Available,Rincy,Not Viewed
9996,Not Won,2026-05-05,Sanju,Insta Ad,LEADS AD,0.0,Plus Two,Other,not provided,Inform Later,...,Python Full Stack,No,CC-AK-OPEN,Ninghalude Qualification Plus Two (open),Bridgeon Admin,2026-05-05,Sanju,Not Available,Sanju,Not Viewed
9997,2026-05-05,2026-05-05,jaiharish,Incoming Call,No Campaign,0.0,Other Course,Other,not provided,CLOSED LOST,...,Python Full Stack,No,No Ad Set,No Ad,jaiharish,2026-05-05,jaiharish,Not Available,jaiharish,Not Viewed
9998,Not Won,2026-05-05,Ambili,Insta Ad,Lookalike LEADS - Copy,0.0,Other Course,Other,not provided,CLOSED LOST,...,Python Full Stack,No,CC-SK-LL - II,Degree Urapichavar (CC-SK-LL) C,Bridgeon Admin,2026-05-05,Bridgeon Admin,Not Available,Ambili,2026-06-05
9999,Not Won,2026-05-05,Sanju,Insta Ad,MAY-AD 1,0.0,Other Course,Other,not provided,CLOSED LOST,...,Python Full Stack,No,SK-BD-CC,Degree Urapichavar (SK-BD-MAY 1),Bridgeon Admin,2026-05-05,Bridgeon Admin,Not Available,Sanju,2026-05-05

## Export the cleaned dataset

In [589]:
save_path = r"C:\Users\user\Desktop\Group project\Data set\CRM_Leads_Cleaned_2.csv"   
df.to_csv(save_path, index=False)
print("Saved Successfully")

Saved Successfully

# Final Cleaning Summary

### What was done

- Missing categorical values  → `Unknown`
- Missing email → `Not Provided`
- Missing campaign values  → `No Campaign`or  `Not Provided` 
- Missing ad set values  → `No Ad Set`
- Missing ad name values → `No Ad`
- Missing descriptions and feedback  → `No Information`
- Missing call metrics → `0`
- Missing won revenue → `0`
- Negative revenue values → `0`
- --Select-- replaced with  → `Unknown`
- -Other- standardized to Other.
- Date/time columns converted to datetime format.
- Placeholder dates used for missing date/time values.
- Duplicate rows checked but not automatically deleted.
- No rows deleted because of missing values.
- Final missing-value and dataset-size checks performed.

### Final workflow

**CRM Leads.csv → Inspect → Clean Missing Values → Convert Data Types → Validate → Export → Power BI**